---
title: "reliability1"
author: "Ruilin Peng"
date: "2025-12-10"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Data Loading from freemocap regarding left foot
```{r}
library(read.gt3x)
library(data.table)

df <- fread("data/recording_15_41_06_gmt+8_by_trajectory.csv")

cols_keep <- c(
  "timestamp",
  "com_left_foot_x", "com_left_foot_y", "com_left_foot_z"
)

df <- df[, ..cols_keep]
```

# Plot the 3 timeseries
```{r}
library(ggplot2)
df[, t := (timestamp - timestamp[1]) / 1e9]   # convert ns → seconds
ggplot(df, aes(x = t, y = com_left_foot_x)) +
  geom_line(color = "red") +
  theme_minimal() +
  labs(title = "Left Foot COM: X coordinate", x = "Time (s)", y = "X (units?)")

```

```{r}
ggplot(df, aes(x = t, y = com_left_foot_y)) +
  geom_line(color = "blue") +
  theme_minimal() +
  labs(title = "Left Foot COM: Y coordinate", x = "Time (s)", y = "Y (units?)")

```

```{r}
ggplot(df, aes(x = t, y = com_left_foot_z)) +
  geom_line(color = "green") +
  theme_minimal() +
  labs(title = "Left Foot COM: Z coordinate", x = "Time (s)", y = "Z (units?)")

```

# Outliers removal
From plots above we can observe outliers, which can significantly influence the correlation afterward.
```{r}
remove_outliers_mad <- function(x, k = 6) {
  med  <- median(x, na.rm = TRUE)
  madv <- mad(x, constant = 1, na.rm = TRUE)
  dev  <- abs(x - med)

  x[dev > k*madv] <- NA
  return(x)
}

```
We first assign NA to data points whose deviation is greater than 6 MADs(Median Absolute Deviation) away from the median
```{r}
df[, com_left_foot_x := remove_outliers_mad(com_left_foot_x)]
df[, com_left_foot_y := remove_outliers_mad(com_left_foot_y)]
df[, com_left_foot_z := remove_outliers_mad(com_left_foot_z)]
```

```{r}
library(zoo)

df[, com_left_foot_x := na.approx(com_left_foot_x, na.rm = FALSE)]
df[, com_left_foot_y := na.approx(com_left_foot_y, na.rm = FALSE)]
df[, com_left_foot_z := na.approx(com_left_foot_z, na.rm = FALSE)]

```
Then we incorporate missing values.
```{r}

ggplot(df, aes(t, com_left_foot_x)) +
  geom_line(color="red") + 
  ggtitle("Left Foot COM X (Filtered)")

ggplot(df, aes(t, com_left_foot_y)) +
  geom_line(color="blue") + 
  ggtitle("Left Foot COM Y (Filtered)")

ggplot(df, aes(t, com_left_foot_z)) +
  geom_line(color="green") + 
  ggtitle("Left Foot COM Z (Filtered)")

```

